version: '3.2'
services:
  php_fpm7:
      container_name: angular_PHP7.X
      restart: always
      build:
          context: .
          dockerfile: Dockerfile
      volumes:
       - /var/www/html/angular-dk:/var/www/html/angular
    #    - /var/www/html/spotiaapp:/var/www/html/spotiaapp
      ports:
       - "8001:80" # Puerto para sitio
      expose:
       - 80 #puerto expuesto por docker